[project]
name = "tablers-benchmark"
version = "0.1.0"
description = "benchmark for tablers"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "pdfplumber>=0.11.9",
    "pymupdf>=1.26.7",
    "tablers>=0.2.0",
]
